parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:react-hooks/recommended'

plugins:
  - import

rules:
  eqeqeq:
    - error
    - always
    - null: ignore

  # eslint-plugin-import
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  import/no-unresolved: error
  import/order:
    - error
    - groups:
        - - builtin
          - external
        - - internal
          - parent
          - sibling
          - index
      newlines-between: always

settings:
  import/resolver: typescript
